apiVersion: apps/v1
kind: Deployment
metadata:
  name: apartments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apartments
  template: 
    metadata:
      labels: 
        app: apartments
    spec:
      containers:
        - name: apartments
          image: kkunle/apartments
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef: 
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: moveaffordably
            - name: MONGO_URI
              value: 'mongodb://apartment-mongo-srv:27017/apartment'
            - name: JWT_KEY
              valueFrom: 
                secretKeyRef:
                # kubectl create secret generic jwt-session --from-literal=JWT_KEY=kunle 
                  name: jwt-session
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: apartments-srv
spec:
  selector:
    app: apartments
  ports:
    - name: apartments
      protocol: TCP
      port: 3000
      targetPort: 3000
